tee: support of allocating DMA shared buffers **not for mainline**
Fix compilation issue:
drivers/tee/optee/rpc.c: In function 'handle_rpc_func_cmd_shm_alloc':
drivers/tee/optee/rpc.c:236:7: error: 'OPTEE_MSG_RPC_SHM_TYPE_KERNEL_GLOBAL'
undeclared (first use in this function)
  case OPTEE_MSG_RPC_SHM_TYPE_KERNEL_GLOBAL:

Fixes: 0c23453b3dcc ("tee: support of allocating DMA shared buffers **not for
mainline**")
Signed-off-by: Igor Opaniuk <igor.opaniuk@linaro.org>